// web/nuxt/components/LangToggle.vue
<template>
  <div class="lang-toggle">
    <button
      class="lang-btn"
      :class="{ active: lang === 'zh' }"
      @click="setLang('zh')"
    >中</button>
    <button
      class="lang-btn"
      :class="{ active: lang === 'en' }"
      @click="setLang('en')"
    >EN</button>
  </div>
</template>

<script setup lang="ts">
const { lang, setLang } = useLang()
</script>

// web/sveltekit/src/lib/components/LangToggle.svelte
<script lang="ts">
  import { lang } from '$lib/lang'
</script>

<div class="lang-toggle">
  <button
    class="lang-btn"
    class:active={$lang === 'zh'}
    on:click={() => lang.set('zh')}
  >中</button>
  <button
    class="lang-btn"
    class:active={$lang === 'en'}
    on:click={() => lang.set('en')}
  >EN</button>
</div>
